seed: 42
stage: finetune_cv
use_wandb: false

data:
  patch_size: 9

  finetune_path:
    - ../data/O013257.npz
    - ../data/O013490.npz
    - ../data/O012791.npz

  norm_load_path: results/transfer_learning/checkpoints_modified/pretrain/norm_stats.npz
  pretrained_checkpoint_dir: results/transfer_learning/checkpoints_modified/pretrain

dataloader_train:
  batch_size: 1024
  num_workers: 4
  shuffle: true

dataloader_val:
  batch_size: 1024
  num_workers: 4
  shuffle: false

optimizer:
  lr: 0.0001

autoencoder:
  n_input_channels: 8
  embedding_size: 8

checkpoint:
  save_top_k: 3
  monitor: val_loss
  mode: min
  filename: finetune-{epoch:03d}-{val_loss:.4f}
  dirpath: results/transfer_learning/checkpoints_modified/finetune

wandb:
  project: lab2-autoencoder
  name: finetune

trainer:
  max_epochs: 20
  log_every_n_steps: 200