seed: 42
stage: pretrain
use_wandb: false

data:
  patch_size: 9
  train_fraction: 0.8

  pretrain_path:
    - ../data/O002539.npz
    - ../data/O002772.npz
    - ../data/O003005.npz
    - ../data/O003238.npz
    - ../data/O003471.npz
    - ../data/O007199.npz
    - ../data/O007432.npz
    - ../data/O007665.npz
    - ../data/O007898.npz
    - ../data/O008131.npz
    - ../data/O008364.npz
    - ../data/O008597.npz
    - ../data/O008830.npz
    - ../data/O012558.npz
    - ../data/O013024.npz
    - ../data/O013723.npz
    - ../data/O013956.npz
    - ../data/O014189.npz
    - ../data/O017917.npz
    - ../data/O018150.npz
    - ../data/O018383.npz
    - ../data/O018616.npz
    - ../data/O018849.npz
    - ../data/O019082.npz
    - ../data/O019315.npz
    - ../data/O023276.npz
    - ../data/O023509.npz
    - ../data/O023742.npz
    - ../data/O023975.npz
    - ../data/O024208.npz
    - ../data/O024441.npz
    - ../data/O024674.npz
    - ../data/O024907.npz
    - ../data/O028635.npz
    - ../data/O028868.npz
    - ../data/O029334.npz
    - ../data/O029567.npz
    - ../data/O029800.npz
    - ../data/O030033.npz
    - ../data/O033761.npz
    - ../data/O033994.npz
    - ../data/O034227.npz
    - ../data/O034460.npz
    - ../data/O034693.npz
    - ../data/O034926.npz
    - ../data/O035159.npz
    - ../data/O035392.npz
    - ../data/O039120.npz
    - ../data/O039353.npz
    - ../data/O039586.npz
    - ../data/O039819.npz
    - ../data/O040052.npz
    - ../data/O040285.npz
    - ../data/O040518.npz
    - ../data/O040751.npz
    - ../data/O044479.npz
    - ../data/O044712.npz
    - ../data/O044945.npz
    - ../data/O045178.npz
    - ../data/O045411.npz
    - ../data/O045644.npz
    - ../data/O045877.npz
    - ../data/O049838.npz
    - ../data/O050071.npz
    - ../data/O050304.npz
    - ../data/O050537.npz
    - ../data/O050770.npz
    - ../data/O051003.npz
    - ../data/O051236.npz
    - ../data/O055197.npz
    - ../data/O055430.npz
    - ../data/O055663.npz
    - ../data/O055896.npz
    - ../data/O056129.npz
    - ../data/O056362.npz
    - ../data/O056595.npz
    - ../data/O060323.npz
    - ../data/O060556.npz
    - ../data/O060789.npz
    - ../data/O061022.npz
    - ../data/O061255.npz
    - ../data/O061488.npz
    - ../data/O061721.npz
    - ../data/O061954.npz
    - ../data/O065915.npz
    - ../data/O066148.npz
    - ../data/O066381.npz
    - ../data/O066614.npz
    - ../data/O066847.npz
    - ../data/O067080.npz
    - ../data/O067313.npz
    - ../data/O071041.npz
    - ../data/O071274.npz
    - ../data/O071507.npz
    - ../data/O071740.npz
    - ../data/O071973.npz
    - ../data/O072206.npz
    - ../data/O072439.npz
    - ../data/O072672.npz
    - ../data/O076400.npz
    - ../data/O076633.npz
    - ../data/O076866.npz
    - ../data/O077099.npz
    - ../data/O077332.npz
    - ../data/O077798.npz
    - ../data/O081759.npz
    - ../data/O081992.npz
    - ../data/O082225.npz
    - ../data/O082458.npz
    - ../data/O082691.npz
    - ../data/O082924.npz
    - ../data/O083157.npz
    - ../data/O087118.npz
    - ../data/O087351.npz
    - ../data/O087584.npz
    - ../data/O087817.npz
    - ../data/O088050.npz
    - ../data/O088283.npz
    - ../data/O088516.npz
    - ../data/O092477.npz
    - ../data/O092710.npz
    - ../data/O092943.npz
    - ../data/O093176.npz
    - ../data/O093409.npz
    - ../data/O093642.npz
    - ../data/O093875.npz
    - ../data/O097836.npz
    - ../data/O098069.npz
    - ../data/O098302.npz
    - ../data/O098535.npz
    - ../data/O098768.npz
    - ../data/O099234.npz
    - ../data/O102962.npz
    - ../data/O103195.npz
    - ../data/O103428.npz
    - ../data/O103661.npz
    - ../data/O103894.npz
    - ../data/O104127.npz
    - ../data/O104360.npz
    - ../data/O104593.npz
    - ../data/O108321.npz
    - ../data/O108554.npz
    - ../data/O108787.npz
    - ../data/O109020.npz
    - ../data/O109253.npz
    - ../data/O109486.npz
    - ../data/O109719.npz
    - ../data/O113680.npz
    - ../data/O113913.npz
    - ../data/O114146.npz
    - ../data/O114379.npz
    - ../data/O114612.npz
    - ../data/O114845.npz
    - ../data/O115078.npz
    - ../data/O119039.npz
    - ../data/O119272.npz
    - ../data/O119505.npz
    - ../data/O119738.npz
    - ../data/O119971.npz
    - ../data/O120204.npz
    - ../data/O120437.npz

  norm_save_path: results/transfer_learning/checkpoints_modified/pretrain/norm_stats.npz

dataloader_train:
  batch_size: 1024
  num_workers: 4
  shuffle: True

dataloader_val:
  batch_size: 1024
  num_workers: 4
  shuffle: False

optimizer:
  lr: 0.001

autoencoder:
  n_input_channels: 8
  embedding_size: 8

checkpoint:
  save_top_k: 3
  monitor: 'val_loss'
  mode: 'min'
  filename: 'pretrain-{epoch:03d}-{val_loss:.4f}'
  dirpath: 'results/transfer_learning/checkpoints_modified/pretrain'

wandb:
  project: 'lab2-autoencoder'
  name: 'pretrain'

trainer:
  max_epochs: 20
  log_every_n_steps: 200
